apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-same-ns
  namespace: test-app-2
spec:
  selector:
    matchLabels:
      app: example-2
  replicas: 2

  template:
    metadata:
      labels:
        app: example-2
    spec:
      containers:
      - name: example-2
        image: nginx:latest
        ports:
        - containerPort: 80

---
# Service to allow the port-forward
apiVersion: v1
kind: Service
metadata:
  name: example-same-ns
  namespace: test-app-2
spec:
  selector:
    app: example-2
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
